// Stores and restores the pretex equation-render cache (Docker volume
// mra-pretex-cache) as a GitHub Release asset.  The first person to build
// a repo pays the full ~45-min cost; every subsequent fresh server restore
// the cache in ~30 s and finishes the full build in 2-5 min.
//
// Cache key: pretex-cache-{owner}-{repo}-{sha8}
// Storage:   GitHub Releases on PROOFDESK_CACHE_REPO (defaults to main repo)
// Auth:      GITHUB_PERSONAL_TOKEN (needs repo scope)

import { exec } from 'child_process';
import { promisify } from 'util';
import https from 'https';
import http from 'http';
import fs from 'fs/promises';
import { createWriteStream } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { getProofdeskDataRoot } from '../utils/dataPaths.js';

const execAsync = promisify(exec);
const __filename = fileURLToPath(import.meta.url);

const DOCKER_VOLUME = 'mra-pretex-cache';

class GitHubCacheStore {
  constructor() {
    this.token     = process.env.GITHUB_PERSONAL_TOKEN || '';
    this.cacheRepo = process.env.PROOFDESK_CACHE_REPO  || 'harsharajkumar/proofdesk';
    this.enabled   = !!this.token;

    if (!this.enabled) {
      console.log('[GitHubCache] GITHUB_PERSONAL_TOKEN not set — pretex cache upload/restore disabled');
    }
  }

  _tag(owner, repo, sha) {
    return `pretex-cache-${owner}-${repo}-${sha.slice(0, 8)}`;
  }

  /* ── Restore: download release asset → inject into Docker volume ─────────── */

  async checkAndRestore(owner, repo, sha) {
    if (!this.enabled || !sha) return false;

    // Skip if the volume already has cached equations
    try {
      const { stdout } = await execAsync(
        `docker run --rm -v ${DOCKER_VOLUME}:/cache alpine sh -c "ls /cache 2>/dev/null | wc -l"`,
        { timeout: 15000 }
      );
      if (parseInt(stdout.trim(), 10) > 0) {
        console.log('[GitHubCache] Volume already populated — skipping restore');
        return true;
      }
    } catch { /* docker unavailable */ }

    const tag = this._tag(owner, repo, sha);
    console.log(`[GitHubCache] Looking for release ${tag} ...`);

    try {
      const release = await this._getRelease(tag);
      if (!release) {
        console.log('[GitHubCache] No cached release found — full build required');
        return false;
      }

      const asset = release.assets?.find(a => a.name === 'pretex-cache.tar.gz');
      if (!asset) return false;

      console.log(`[GitHubCache] Restoring pretex cache (${Math.round(asset.size / 1024 / 1024)} MB) ...`);
      const tmpFile = path.join(getProofdeskDataRoot(), `pretex-cache-${Date.now()}.tar.gz`);

      await this._downloadAsset(asset.url, tmpFile);

      // Inject into the Docker volume by extracting inside an alpine container
      await execAsync(
        `docker run --rm -v ${DOCKER_VOLUME}:/cache -v "${tmpFile}:/tmp/cache.tar.gz:ro" alpine sh -c "tar xzf /tmp/cache.tar.gz -C / 2>/dev/null || true"`,
        { timeout: 300000 }
      );
      await fs.unlink(tmpFile).catch(() => {});
      console.log('[GitHubCache] Pretex cache restored — build will skip equation rendering');
      return true;
    } catch (err) {
      console.warn('[GitHubCache] Restore failed:', err.message);
      return false;
    }
  }

  /* ── Save: tar Docker volume → create GitHub Release → upload asset ──────── */

  async save(owner, repo, sha) {
    if (!this.enabled || !sha) return;

    const tag = this._tag(owner, repo, sha);

    // Don't re-upload if the release already exists
    const existing = await this._getRelease(tag).catch(() => null);
    if (existing) {
      console.log(`[GitHubCache] Release ${tag} already exists — skipping upload`);
      return;
    }

    const tmpFile = path.join(getProofdeskDataRoot(), `pretex-cache-${Date.now()}.tar.gz`);
    console.log(`[GitHubCache] Packaging pretex cache for upload ...`);

    try {
      // Tar the entire volume content
      const tmpDir = getProofdeskDataRoot();
      await execAsync(
        `docker run --rm -v ${DOCKER_VOLUME}:/cache -v "${tmpDir}:/out" alpine tar czf "/out/${path.basename(tmpFile)}" /cache`,
        { timeout: 300000 }
      );

      const stat = await fs.stat(tmpFile);
      console.log(`[GitHubCache] Cache tarball: ${Math.round(stat.size / 1024 / 1024)} MB`);

      const release = await this._createRelease(
        tag,
        `Pretex equation cache for ${owner}/${repo} @ ${sha.slice(0, 8)}\n\nAuto-generated by Proofdesk — do not edit.`
      );
      await this._uploadAsset(release.upload_url, tmpFile, 'pretex-cache.tar.gz', stat.size);
      console.log(`[GitHubCache] Cache uploaded as release ${tag}`);
    } catch (err) {
      console.warn('[GitHubCache] Upload failed (non-fatal):', err.message);
    } finally {
      await fs.unlink(tmpFile).catch(() => {});
    }
  }

  /* ── GitHub API helpers ──────────────────────────────────────────────────── */

  _apiRequest(method, path, body = null) {
    return new Promise((resolve, reject) => {
      const opts = {
        hostname: 'api.github.com',
        path,
        method,
        headers: {
          'Authorization': `token ${this.token}`,
          'User-Agent':    'proofdesk-cache/1.0',
          'Accept':        'application/vnd.github.v3+json',
          ...(body ? { 'Content-Type': 'application/json' } : {}),
        },
      };
      const req = https.request(opts, (res) => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => {
          if (res.statusCode === 404) return resolve(null);
          if (res.statusCode >= 400) return reject(new Error(`GitHub API ${res.statusCode}: ${data}`));
          try { resolve(JSON.parse(data)); } catch { resolve(data); }
        });
      });
      req.on('error', reject);
      if (body) req.write(JSON.stringify(body));
      req.end();
    });
  }

  async _getRelease(tag) {
    const [owner, repo] = this.cacheRepo.split('/');
    return this._apiRequest('GET', `/repos/${owner}/${repo}/releases/tags/${tag}`);
  }

  async _createRelease(tag, body) {
    const [owner, repo] = this.cacheRepo.split('/');
    return this._apiRequest('POST', `/repos/${owner}/${repo}/releases`, {
      tag_name:   tag,
      name:       tag,
      body,
      draft:      false,
      prerelease: true,
    });
  }

  async _uploadAsset(uploadUrl, filePath, name, size) {
    // uploadUrl looks like: https://uploads.github.com/repos/.../releases/.../assets{?name,label}
    const base = uploadUrl.replace(/\{.*\}/, '');
    const url  = new URL(`${base}?name=${encodeURIComponent(name)}`);

    const fileHandle = await fs.open(filePath, 'r');
    const fileStream = fileHandle.createReadStream();

    return new Promise((resolve, reject) => {
      const opts = {
        hostname: url.hostname,
        path:     url.pathname + url.search,
        method:   'POST',
        headers: {
          'Authorization': `token ${this.token}`,
          'User-Agent':    'proofdesk-cache/1.0',
          'Content-Type':  'application/gzip',
          'Content-Length': size,
        },
      };
      const req = https.request(opts, (res) => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', async () => {
          await fileHandle.close().catch(() => {});
          if (res.statusCode >= 400) return reject(new Error(`Upload failed ${res.statusCode}: ${data}`));
          try { resolve(JSON.parse(data)); } catch { resolve(data); }
        });
      });
      req.on('error', async (err) => {
        await fileHandle.close().catch(() => {});
        reject(err);
      });
      fileStream.pipe(req);
    });
  }

  async _downloadAsset(assetUrl, dest) {
    // GitHub asset URLs redirect to S3; must follow redirects
    const follow = (url, redirects = 5) => new Promise((resolve, reject) => {
      if (redirects === 0) return reject(new Error('Too many redirects'));
      const mod = url.startsWith('https') ? https : http;
      mod.get(url, {
        headers: {
          'Authorization': `token ${this.token}`,
          'User-Agent':    'proofdesk-cache/1.0',
          'Accept':        'application/octet-stream',
        },
      }, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          res.resume();
          return follow(res.headers.location, redirects - 1).then(resolve, reject);
        }
        if (res.statusCode !== 200) {
          res.resume();
          return reject(new Error(`Download failed: HTTP ${res.statusCode}`));
        }
        const file = createWriteStream(dest);
        res.pipe(file);
        file.on('finish', () => file.close(resolve));
        file.on('error', reject);
      }).on('error', reject);
    });

    return follow(assetUrl);
  }
}

export default new GitHubCacheStore();
